### ISSUE TITLE
Remove URI string from the prod folder

### ISSUE THREAD

**Issue by kfiryahav** [liathaf/zviafood-backend#1]
You don't need to put sensitive data like URI exposure, instead put it on .env file as an environment variable.

**Comment by liathaf** [comment]
Thank you for your comment. I have made some changes.

**Comment by kfiryahav** [comment]
Hey, you can make your code easier to understand and to manage.

Pay attention to structure, you organized the code with unclear hierarchy.

For example, you put the controller within the api route folder.

If you want to see clear hierarchy, you can check my last backend PRs.
It makes your code more modular and more maintainable.

Of its isn't clear enough, feel free to ask more questions.
